<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <RootNamespace>GarageGroup.Infra</RootNamespace>
    <AssemblyName>GarageGroup.Infra.Dataverse.Api.Abstractions.Impersonate</AssemblyName>
    <Version>2.2.0</Version>
  </PropertyGroup>

</Project>