<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);IDE0130;CA1859</NoWarn>
    <RootNamespace>GarageGroup.Infra</RootNamespace>
    <AssemblyName>GarageGroup.Infra.Dataverse.Api.Abstractions</AssemblyName>
    <Version>3.17.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Api.Abstractions.ChangeSetExecute/Api.Abstractions.ChangeSetExecute.csproj" />
    <ProjectReference Include="../Api.Abstractions.EmailSend/Api.Abstractions.EmailSend.csproj" />
    <ProjectReference Include="../Api.Abstractions.EntityCreate/Api.Abstractions.EntityCreate.csproj" />
    <ProjectReference Include="../Api.Abstractions.EntityDelete/Api.Abstractions.EntityDelete.csproj" />
    <ProjectReference Include="../Api.Abstractions.EntityGet/Api.Abstractions.EntityGet.csproj" />
    <ProjectReference Include="../Api.Abstractions.EntitySetGet/Api.Abstractions.EntitySetGet.csproj" />
    <ProjectReference Include="../Api.Abstractions.EntityUpdate/Api.Abstractions.EntityUpdate.csproj" />
    <ProjectReference Include="../Api.Abstractions.FetchXml/Api.Abstractions.FetchXml.csproj" />
    <ProjectReference Include="../Api.Abstractions.Impersonate/Api.Abstractions.Impersonate.csproj" />
    <ProjectReference Include="../Api.Abstractions.Search/Api.Abstractions.Search.csproj" />
    <ProjectReference Include="../Api.Abstractions.WhoAmI/Api.Abstractions.WhoAmI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GarageGroup.Infra.HealthCheck.Api.Contract.Ping" Version="1.0.0" />
  </ItemGroup>

</Project>