<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);IDE0130;CA1859</NoWarn>
    <RootNamespace>GarageGroup.Infra</RootNamespace>
    <AssemblyName>GarageGroup.Infra.Dataverse.Api</AssemblyName>
    <Version>3.21.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../api-abstractions/Api.Abstractions/Api.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.7" />
    <PackageReference Include="PrimeFuncPack.Dependency" Version="2.1.0" />
    <PackageReference Include="PrimeFuncPack.Primitives.Pipeline" Version="3.0.0" />
    <PackageReference Include="PrimeFuncPack.Primitives.Strings" Version="3.0.0" />
  </ItemGroup>

</Project>